# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: code
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    # Human Aliases

    # List all Aliases, and these comments
    aliases: '!cat ~/.config/gh/aliases.yml | sed -n -e "/# Human Aliases/,\$p" | grep -e "^    \\|^    #"'

    # Forks a repo with the name "owner/repository" and renames the form to "owner--repository"
    forkrn: "!f() { gh repo fork $1 --clone=false --remote=false --name=$(echo $1 | sed 's/\//--/g'); }; f"
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
