# See https://starship.rs/config/ for all available configurations

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶ "

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "
disabled = false

[time]
disabled = false

[aws]
disabled = true
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
disabled = true
symbol = "  "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[custom.dnf_check_updates]
description = "Displays number of available updates via DNF"
command = """
CACHE_FILE=\"$HOME/.cache/dnf_update_count\"
if [[ -f \"$CACHE_FILE\" ]]; then
    DNF_UPDATES=$(cat \"$CACHE_FILE\")
else
    DNF_UPDATES=0
fi
if (( $DNF_UPDATES > 0 )); then
    DNF_UPDATES_SYMBOL="󰏖"
else
    DNF_UPDATES_SYMBOL="󰏗"
fi
echo "$DNF_UPDATES_SYMBOL $DNF_UPDATES"
"""
format = "$output "
shell = ["bash", "--noprofile", "--norc"]
when = true
ignore_timeout = true

[shell]
disabled = true

