[projects."/home/robert/Repositories/github.com/robellegate/resume"]
trust_level = "trusted"

[projects."/home/robert/Repositories/github.com/robellegate/lg-spotify-playlist-art-agent"]
trust_level = "trusted"

[projects."/home/robert/Repositories/github.com/robellegate/album_art_agent_bak"]
trust_level = "trusted"

[projects."/home/robert/Repositories/github.com/robellegate/album_art_agent"]
trust_level = "trusted"
